# 50Wilu's Travis script taken from the FF2 Official GitHub repo. Never heard of Travis but it sounds neat so I'll use it! Thanks 50Wilu!

# Use the new container-based infrastructure
sudo: false

# Install some apt packages needed for spcomp
addons:

    apt:
        packages:
            - lib32stdc++6

# Set the build environment
env:
    - SMVERSION=1.8 # Stable
    - SMVERSION=1.9 # Unstable

# And compile!
install:
    - wget --input-file=http://sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux
    - tar -xvzf $(cat sourcemod-latest-linux)
before_script:
    - wget "https://raw.githubusercontent.com/asherkin/TF2Items/master/pawn/tf2items.inc" -O sourcemod/scripting/include/tf2items.inc
    - wget "http://www.doctormckay.com/download/scripting/include/morecolors.inc" -O sourcemod/scripting/include/morecolors.inc
    - wget "https://raw.githubusercontent.com/asherkin/SteamTools/master/plugin/steamtools.inc" -O sourcemod/scripting/include/steamtools.inc
    - wget "https://bitbucket.org/GoD_Tony/updater/raw/default/include/updater.inc" -O sourcemod/scripting/include/updater.inc
    - wget "https://raw.githubusercontent.com/FlaminSarge/tf2attributes/master/tf2attributes.inc" -O sourcemod/scripting/include/tf2attributes.inc
    - wget "https://github.com/VoiDeD/sourcemod-transitional-helpers/archive/master.zip" -O sourcemod-transitional-helpers-master.zip
    - unzip sourcemod-transitional-helpers-master.zip
    - mkdir thelpers sourcemod/scripting/include/thelpers
    - mv sourcemod-transitional-helpers-master/thelpers/* sourcemod/scripting/include/thelpers

    - chmod +x scripting/spcomp
    - mkdir compiled sourcemod/scripting/compiled/bossrush
    - cd sourcemod/scripting/
script: ./compile.sh bossrush.sp

# Notifications
notifications:
email: false